# Generated by Django 3.0.2 on 2020-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drName', models.CharField(max_length=50)),
                ('drmobNo', models.CharField(max_length=50)),
                ('drEmail', models.CharField(max_length=50)),
                ('drPassword', models.CharField(max_length=50)),
                ('drLicense', models.CharField(max_length=50)),
                ('drCity', models.CharField(max_length=50)),
                ('drPincode', models.IntegerField()),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
    ]
