# Generated by Django 3.0.2 on 2020-03-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='drEmail',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
