# Generated by Django 3.0.2 on 2020-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200320_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='drEmail',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
