# Generated by Django 3.0.2 on 2020-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200320_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('cName', models.CharField(max_length=50)),
                ('cmobNo', models.CharField(max_length=50)),
                ('cEmail', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('cAddress', models.CharField(max_length=50)),
                ('cCity', models.CharField(max_length=50)),
                ('cPincode', models.CharField(max_length=50)),
                ('cPassword', models.IntegerField()),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
    ]
