# Generated by Django 3.0.2 on 2020-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_chemist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='cPassword',
            field=models.CharField(max_length=30),
        ),
    ]
